name: lint

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run lint
        env:
          NODE_ENV: local
